# Generated by Django 2.0.7 on 2018-07-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adyengo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='currency_code',
            field=models.CharField(choices=[('EUR', 'Euro')], default='EUR', max_length=3),
        ),
        migrations.AlterField(
            model_name='notification',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('ebanking_FI', 'Finnish E-Banking'), ('mc', 'Master Card'), ('giropay', 'GiroPay'), ('maestro', 'Maestro'), ('directdebit_NL', 'Direct Debit (Netherlands)'), ('bankTransfer_NL', 'Dutch Banktransfer'), ('bcmc', 'Bancontact card'), ('paypal', 'PayPal'), ('dotpay', 'Dotpay'), ('visa', 'Visa'), ('amex', 'Amex'), ('bankTransfer', 'All banktransfers'), ('sepadirectdebit', 'SEPA Direct Debit'), ('elv', 'ELV'), ('card', 'All debit and credit cards'), ('ideal', 'iDEAL'), ('diners', 'Diners Club'), ('bankTransfer_DE', 'German Banktransfer'), ('directEbanking', 'SofortUberweisung'), ('discover', 'Discover'), ('bankTransfer_IBAN', 'International Bank Transfer (IBAN)')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='recurringpaymentresult',
            name='result_code',
            field=models.CharField(choices=[('Received', 'Received'), ('Authorised', 'Authorised'), ('Refused', 'Refused'), ('Error', 'Error')], max_length=30),
        ),
        migrations.AlterField(
            model_name='session',
            name='country_code',
            field=models.CharField(choices=[('GB', 'United Kingdom'), ('NL', 'Netherlands'), ('DE', 'Germany'), ('BE', 'Belgium')], max_length=2),
        ),
        migrations.AlterField(
            model_name='session',
            name='currency_code',
            field=models.CharField(choices=[('EUR', 'Euro')], default='EUR', max_length=3),
        ),
        migrations.AlterField(
            model_name='session',
            name='page_type',
            field=models.CharField(choices=[('skip', 'Skip'), ('single', 'Single'), ('multiple', 'Multiple')], default='multiple', max_length=15),
        ),
        migrations.AlterField(
            model_name='session',
            name='recurring_contract',
            field=models.CharField(blank=True, choices=[('RECURRING', 'Recurring'), ('RECURRING,ONECLICK', 'Recurring and One click (user chooses)'), ('ONECLICK', 'One click')], max_length=50),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('hpp_recurring', 'HPP Recurring'), ('api_recurring', 'API Recurring'), ('hpp_regular', 'HPP Regular')], max_length=25),
        ),
        migrations.AlterField(
            model_name='session',
            name='shopper_locale',
            field=models.CharField(blank=True, choices=[('nl_NL', 'Dutch (Holland)'), ('de_DE', 'German (Germany)'), ('nl_BE', 'Dutch (Belgium)'), ('en_GB', 'English (United Kingdom)'), ('fr_BE', 'French (Belgium)')], default='fr', max_length=5),
        ),
        migrations.AlterField(
            model_name='session',
            name='skin_code',
            field=models.CharField(default='Fa3EedeE', max_length=10),
        ),
        migrations.AlterField(
            model_name='sessionallowedpaymentmethods',
            name='method',
            field=models.CharField(choices=[('ebanking_FI', 'Finnish E-Banking'), ('mc', 'Master Card'), ('giropay', 'GiroPay'), ('maestro', 'Maestro'), ('directdebit_NL', 'Direct Debit (Netherlands)'), ('bankTransfer_NL', 'Dutch Banktransfer'), ('bcmc', 'Bancontact card'), ('paypal', 'PayPal'), ('dotpay', 'Dotpay'), ('visa', 'Visa'), ('amex', 'Amex'), ('bankTransfer', 'All banktransfers'), ('sepadirectdebit', 'SEPA Direct Debit'), ('elv', 'ELV'), ('card', 'All debit and credit cards'), ('ideal', 'iDEAL'), ('diners', 'Diners Club'), ('bankTransfer_DE', 'German Banktransfer'), ('directEbanking', 'SofortUberweisung'), ('discover', 'Discover'), ('bankTransfer_IBAN', 'International Bank Transfer (IBAN)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sessionblockedpaymentmethods',
            name='method',
            field=models.CharField(choices=[('ebanking_FI', 'Finnish E-Banking'), ('mc', 'Master Card'), ('giropay', 'GiroPay'), ('maestro', 'Maestro'), ('directdebit_NL', 'Direct Debit (Netherlands)'), ('bankTransfer_NL', 'Dutch Banktransfer'), ('bcmc', 'Bancontact card'), ('paypal', 'PayPal'), ('dotpay', 'Dotpay'), ('visa', 'Visa'), ('amex', 'Amex'), ('bankTransfer', 'All banktransfers'), ('sepadirectdebit', 'SEPA Direct Debit'), ('elv', 'ELV'), ('card', 'All debit and credit cards'), ('ideal', 'iDEAL'), ('diners', 'Diners Club'), ('bankTransfer_DE', 'German Banktransfer'), ('directEbanking', 'SofortUberweisung'), ('discover', 'Discover'), ('bankTransfer_IBAN', 'International Bank Transfer (IBAN)')], max_length=50),
        ),
    ]
