# Generated by Django 2.2.1 on 2019-10-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adyengo', '0003_auto_20191022_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='payment_amount',
            field=models.PositiveIntegerField(),
        ),
    ]
